import Link from "next/link";

export const metadata = { title: "Privacy Policy — LookMe" };

export default function PrivacyPage() {
  return (
    <div className="bg-white min-h-screen max-w-3xl mx-auto px-6 py-16">
      <div className="mb-10">
        <Link href="/" className="text-sm text-neutral-500 hover:text-neutral-900 transition-colors">
          ← Back to LookMe
        </Link>
      </div>

      <h1 className="text-3xl font-bold tracking-tight text-neutral-900 mb-2">Privacy Policy</h1>
      <p className="text-neutral-500 text-sm mb-10">Last updated: May 2026</p>

      <div className="prose prose-neutral max-w-none space-y-8 text-sm leading-relaxed text-neutral-700">

        <section>
          <h2 className="text-base font-bold text-neutral-900 mb-3">1. Information We Collect</h2>
          <p className="mb-2">We collect information you provide directly and information generated by your use of the platform:</p>
          <ul className="list-disc list-inside space-y-2">
            <li><strong>Account data:</strong> Name, email address, password (hashed), country, role (client or worker)</li>
            <li><strong>Order data:</strong> Target URLs, quantities, payment method, service type</li>
            <li><strong>Task data (workers):</strong> Task completion records, proof submissions (screenshots, text), the email addresses declared for review tasks, IP address at submission, user agent</li>
            <li><strong>Payment data:</strong> Wallet balance, transaction history. Card details are processed by Stripe — we do not store raw card numbers.</li>
            <li><strong>Usage data:</strong> Pages visited, timestamps, device type</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-neutral-900 mb-3">2. Why We Collect Review Email Addresses</h2>
          <p>
            When workers accept review tasks, they must declare the email address of the account they will
            use to post the review. We collect and store this email address specifically to:
          </p>
          <ul className="list-disc list-inside space-y-2 mt-2">
            <li>Prevent the same email address from being used to review the same business more than once (which would violate the target platform&apos;s policies and could harm our clients)</li>
            <li>Maintain an audit trail of which accounts were used for which tasks</li>
            <li>Detect and prevent fraud</li>
          </ul>
          <p className="mt-2">
            This email is not shared with clients. It is stored securely and used only for the purposes
            described above.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-neutral-900 mb-3">3. How We Use Your Information</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>To operate and deliver the platform services</li>
            <li>To process payments and payouts</li>
            <li>To verify task completion and prevent fraud</li>
            <li>To calculate and maintain worker trust scores</li>
            <li>To communicate with you about your account and orders</li>
            <li>To comply with legal obligations</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-neutral-900 mb-3">4. Data Sharing</h2>
          <p className="mb-2">We do not sell your personal data. We share data only with:</p>
          <ul className="list-disc list-inside space-y-2">
            <li><strong>Stripe:</strong> For payment processing and worker payouts</li>
            <li><strong>Cloud infrastructure providers:</strong> For hosting and storage (data remains encrypted)</li>
            <li><strong>Law enforcement:</strong> When required by law or to prevent fraud</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-neutral-900 mb-3">5. Data Retention</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>Account data is retained for as long as your account is active</li>
            <li>Task records and proof submissions are retained for 2 years for audit purposes</li>
            <li>Worker email usage records for review tasks are retained indefinitely to prevent duplicate reviews</li>
            <li>Payment records are retained for 7 years to comply with financial regulations</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-neutral-900 mb-3">6. Your Rights</h2>
          <p className="mb-2">Depending on your jurisdiction, you may have the right to:</p>
          <ul className="list-disc list-inside space-y-2">
            <li>Access the personal data we hold about you</li>
            <li>Request correction of inaccurate data</li>
            <li>Request deletion of your account (subject to legal retention obligations)</li>
            <li>Object to or restrict processing</li>
            <li>Data portability</li>
          </ul>
          <p className="mt-2">To exercise these rights, contact us at <a href="mailto:privacy@lookme.io" className="text-neutral-900 underline">privacy@lookme.io</a>.</p>
        </section>

        <section>
          <h2 className="text-base font-bold text-neutral-900 mb-3">7. Security</h2>
          <p>
            We use industry-standard security measures including encrypted connections (HTTPS),
            hashed passwords (bcrypt), JWT authentication with short-lived tokens, and access controls.
            No system is perfectly secure, and we cannot guarantee absolute security.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-neutral-900 mb-3">8. Cookies</h2>
          <p>
            We use essential session cookies to keep you logged in. We do not use third-party
            advertising cookies. You can disable cookies in your browser settings, which may affect
            platform functionality.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-neutral-900 mb-3">9. Children</h2>
          <p>
            LookMe is not intended for users under the age of 18. We do not knowingly collect
            personal data from minors. If you believe a minor has created an account, contact us
            and we will promptly delete it.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-neutral-900 mb-3">10. Contact</h2>
          <p>
            For privacy-related questions or requests, contact our Data Protection Officer at{" "}
            <a href="mailto:privacy@lookme.io" className="text-neutral-900 underline">privacy@lookme.io</a>.
          </p>
        </section>

      </div>

      <div className="mt-12 pt-8 border-t border-neutral-100 flex gap-6">
        <Link href="/terms" className="text-sm text-neutral-500 hover:text-neutral-900 underline underline-offset-2">
          Terms of Service
        </Link>
        <Link href="/register" className="text-sm text-neutral-500 hover:text-neutral-900 underline underline-offset-2">
          Back to Register
        </Link>
      </div>
    </div>
  );
}
